### ISSUE TITLE
id != transmission's torrent id  -- how to specify by tid?

### ISSUE THREAD

**Issue by Astara** [olof/transmission-client#6]
I was trying to access information using Transmission::Client for which I have the transmission "tid", but I don't see how.  It seems there is an 'id' field, but that's just an unrelated number in the packed list of arrays.  I don't see a tid or torrent_id field like one might specify when using to input a command to "transmission-remote" or see when one lists all the torrents using the same.

How can I specify a torrent by it's transmission torrent id?

Thanks!

**Comment by olof** [comment]
I'm so sorry, I have seen this issue because of bad mail filtering on my part! :(

Is this still an issue?

To Transmssion::Client, id is just a string we pass on to the Transmsission RPC. So if the RPC accepts it, it can be used through Transmission::Client, the same as transmission-remote. The id attribute is the numeric ID assigned to the torrent by transmission-daemon at start (i.e. new id each time transmission-daemon is restarted). You can also use a torrent's infohash as the id in the RPC (and by extension, with Transmission::Client).

**Comment by olof** [comment]
Closing, feel free to open a new issue in case of other issues.
